### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by diomed** [nuejs/create-nue#15]
would be nice if you put basic examples of components in starter template

https://nuejs.org/docs/nuejs/component-basics.html

like buttons

list of users and similar

**Comment by tipiirai** [comment]
I'm working on the examples as we speak. The current version is here: https://nuejs.org/docs/nuejs/examples/ — more to come later today or tomorrow.

**Comment by tipiirai** [comment]
Now the [example page](https://nuejs.org/docs/nuejs/examples/) has some more examples. Still more to come

**Comment by tipiirai** [comment]
Loads of more examples on this repository now
