### ISSUE TITLE
Vscode template

### ISSUE THREAD

**Issue by malilat** [nuejs/create-nue#20]
Hello
Can we have a vscode extension for .nue extension ?

**Comment by kon-pas** [comment]
This is far from perfect, but you can associate all `.nue` files with XML. VSCode will syntax highlight them as if they were XML. Paste the following to the `settings.json` in VSCode:
```json
"files.associations": {
  "*.nue": "xml"
},
```

To mute XML syntax errors in `.nue` files, you can disable validation for them, like so:
```json
"xml.validation.filters": [
  {
    "pattern": "**.nue",
    "enabled": false,
  },
],
```
Additionaly, to highlight JS in `<style>` tags, you can install [this extension](https://marketplace.visualstudio.com/items?itemName=PaulGomez.cdata-js-highlighter).

![nue](https://github.com/nuejs/create-nue/assets/80765461/babd31e7-8d39-47ba-9aa2-7697b026177d)

**Comment by malilat** [comment]
thank you very much for this tip, it will help a lot of people

**Comment by tipiirai** [comment]
Now referenced on the docs as well: http://localhost:8080/docs/nuejs/getting-started.html

Thanks a ton @kon-pas !
