### ISSUE TITLE
NUE Live-Server

### ISSUE THREAD

**Issue by Axellarator** [nuejs/create-nue#24]
## NUE Live-Server Solution

> This is a pretty raw hack that works with Chromium.

### Install Live-Server in **create-nue** directory
>npm install live-server 

### We need to modify Live-Server

1. Goto: `create-nue/node_modules/live-server`
2. Open `index.js`
3. Search for `/body`
4. Add: 
```var injectCandidates = [ new RegExp("</main>", "i"),  new RegExp("</body>", "i"), ... ```We need `</main>`so that the `injected.html` process works 
5. Save it and go back to create-nue/scripts
6. Install `live.js` 
 ```
import liveServer from 'live-server'

export default async function (){
  let server = liveServer.start({
    port: 8080,
    host: "0.0.0.0",
    root: "./www",
    open: true,
    ignore: './node_modules, ./scripts',
    file: "index.html",
    wait: 1000,
    mount: [[ "node_modules","scripts" ]], 
    logLevel: 3,
    noCssInject: true,
    middleware: [function(req, res, next) { next(); }] 
  });
}
```
7. Goto `create-nue`
8. Modify `package.json`. 
9. Insert `"live"` in `scripts`
```{
  "name": "create-nue",
  "type": "module",
  "version": "0.1.4",
  "homepage": "https://github.com/Axellarator/create-nue",
  "description": "A recommended way to start a Nue project",
  "repository": {
    "url": "https://github.com/Axellarator/create-nue.git",
    "type": "git"
  },
  "bin": {
    "create-nue": "./scripts/init.js"
  },
  "scripts": {
    "start": "./scripts/cli.js start",
    "live": "./scripts/cli.js live",
    "minify": "./scripts/cli.js minify",
    "render": "./scripts/cli.js render",
    "compile": "./scripts/cli.js compile",
    "serve": "./scripts/cli.js serve"
  },
  "dependencies": {
    "chokidar": "^3.5.3",
    "js-yaml": "^4.1.0",
    "live-server": "^1.2.2",
    "nuejs-core": "^0.1.0",
    "websocket": "^1.0.34"
  }
}
```
## Start it with `npm run live`

`npm run start` still works as indent.
`npm run render` or` npm run compile` isn't done automatically. You are still on your own here. The render process creates a new index.html and Live-server will later on reload your browser. 

A simpler solution is i.e. Tab Reloader add-on for Firefox. Browser reloader are available for Chrome, Safari and others.

**Comment by tipiirai** [comment]
Nue now has "universal live-reload" with the release of Nuekit: https://nuejs.org/blog/nuekit-010/
