### ISSUE TITLE
NOTE: This repository is about to change

### ISSUE THREAD

**Issue by tipiirai** [nuejs/create-nue#27]
Hey fellow devs,

I want to inform all contributors that the repository structure is going to change quite drastically in approximately two weeks. Currently the goal of this project is pretty vaque and it does not serve well for the purpose of starting out with a new Nue project. The upcoming version `1.0.0-beta` will be a major change and showcases more clearly how websites are created with Nue. It is based on semantic styling and Markdown files. I will write a more detailed blog entry about this before pushing the new branch to the repository.

**Comment by xland** [comment]
> it does not serve well for the purpose of starting out with a new Nue project
Yes.

**Comment by tipiirai** [comment]
Additional 1-2 weeks needed. Writing this blog entry about Tailwind took longer than I expected:

https://nuejs.org/blog/tailwind-vs-semantic-css/

**Comment by JensRoland** [comment]
Sounds good, I ran into several issues with this repo but now I'll just wait for the next iteration instead.

In particular: Where does persistence fit in? If the demo app is a blog, the first thing I would do is connect to a database of blog posts (yes, I know for something as simple as a blog we are often better off just authoring posts in Markdown, but in the general case of building a site or app, a DB is often the better choice); with Bun you can use `import { Database } from "bun:sqlite";` and go from there, creating your own model and importing it..... where? And how? In the current create-nue project it wasn't clear where I would do this; in the component? Merge it into the `data` object in `render.js`? Or...? The way imports work and the way component scope/building works, there are a lot of ways that seem like they might work, but don't. So I would like to understand this part better.

**Comment by luckybai** [comment]
> Sounds good, I ran into several issues with this repo but now I'll just wait for the next iteration instead.
> 
> In particular: Where does persistence fit in? If the demo app is a blog, the first thing I would do is connect to a database of blog posts (yes, I know for something as simple as a blog we are often better off just authoring posts in Markdown, but in the general case of building a site or app, a DB is often the better choice); with Bun you can use `import { Database } from "bun:sqlite";` and go from there, creating your own model and importing it..... where? And how? In the current create-nue project it wasn't clear where I would do this; in the component? Merge it into the `data` object in `render.js`? Or...? The way imports work and the way component scope/building works, there are a lot of ways that seem like they might work, but don't. So I would like to understand this part better.

I don't think we need a database for that. Similar to most static site generators (SSG), the articles in the blog are directly saved on the server in a markdown-like format.

**Comment by Yc-Chen** [comment]
I wish to see examples on how to make use of other packages under `node_modules`. Since the serving directory is `www`, should I copy packages under `node_modules` to `www`, or is there a better practice?

**Comment by JensRoland** [comment]
> I don't think we need a database for that. Similar to most static site generators (SSG), the articles in the blog are directly saved on the server in a markdown-like format.

That's why I wrote "_yes, I know for something as simple as a blog we are often better off just authoring posts in Markdown, but in the general case of building a site or app, a DB is often the better choice_"

I want to build sites that are far more dynamic and data-rich than the blog example, sites where a database _is_ the right choice, and I was hoping for advice on where to integrate that.

**Comment by tipiirai** [comment]
Closing this issue, since the repository has indeed changed now (dramatically) with the Nuekit release: https://nuejs.org/blog/nuekit-010/
