### ISSUE TITLE
My click did not trigger

### ISSUE THREAD

**Issue by whqgo** [nuejs/create-nue#28]
node v16.20.0

<button @click="count++">
  <p :if="!count">No clicks yet</p>
  <p :else-if="count == 1">First click!</p>
  <p :else-if="count == 2">Nice. Another one.</p>
  <p :else>Clicks: { count }</p>
  <script>count = 0</script>
</button>

**Comment by tipiirai** [comment]
Hmm. This should work. Here's a working example: https://nuejs.org/docs/nuejs/examples/#counter

The count increases on the button. Please hover out to see it. Tru to not mind the ugly hover effect.
