### ISSUE TITLE
Routing Issue with the blog example

### ISSUE THREAD

**Issue by siemato** [nuejs/create-nue#31]
I've had an issue navigating using the back-navigation on https://nuejs.org/@nextjs-blog/ 

After entering a story, I cannot navigate to the previous (index) page via the back button. This behavior is reproducible across FF and Chrome. 

The observable behavior is jumping to the previous vertical scroll position, but the page content does change.

**Comment by tipiirai** [comment]
I'm going to push all these templates into a dedicated subdomain, such as `nextjs-blog.nuejs.org` to avoid conflicts between the parent site router and the template router. This will solve the issue.

**Comment by siemato** [comment]
Sounds good. I'll close this one then.
