### ISSUE TITLE
Switch git clone command to https in get started docs

### ISSUE THREAD

**Issue by harismh** [nuejs/create-nue#4]
I know the current steps to get started are temporary until npx/bunx comes along. But, should we replace `git clone git@github.com:nuejs/create-nue.git` with `git clone https://github.com/nuejs/create-nue.git`? The latter leads to a simpler operation and doesn't require whitelisting, etc. Happy to open up a PR 🙂.

<img width="703" alt="Screenshot 2023-09-15 at 09 45 32" src="https://github.com/nuejs/create-nue/assets/19330576/2425761d-ce54-4c59-b4ab-2df7556714ea">

**Comment by tipiirai** [comment]
This was fixed last week. Thanks for bringing this up!
